# fly.toml app configuration file generated for rdc on 2025-01-12T14:35:02-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rdc'
primary_region = 'gdl'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_URL = 'https://rdc.fly.dev'
  APP_ENV = 'production'
  APP_DEBUG = 'true'
  DB_CONNECTION= 'pgsql'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
